"""new column for table

Revision ID: 73186a8cd2a8
Revises: bd426f05e656
Create Date: 2026-08-13 16:37:12.895885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73186a8cd2a8'
down_revision: Union[str, Sequence[str], None] = 'bd426f05e656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('total_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'total_size')
    # ### end Alembic commands ###
