"""expand projects model

Revision ID: bd426f05e656
Revises: d49c075f37b7
Create Date: 2026-08-09 15:59:20.522406

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd426f05e656"
down_revision: Union[str, Sequence[str], None] = "d49c075f37b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("name", sa.String(), nullable=False))
    op.add_column("documents", sa.Column("size", sa.Integer(), nullable=False))
    op.add_column("documents", sa.Column("s3_key", sa.String(), nullable=False))
    op.add_column("documents", sa.Column("doc_type", sa.String(), nullable=False))
    op.drop_constraint(
        op.f("documents_project_id_fkey"), "documents", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "documents", "projects", ["project_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("project_members_user_id_fkey"), "project_members", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("project_members_project_id_fkey"), "project_members", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "project_members", "projects", ["project_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "project_members", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("projects", sa.Column("name", sa.String(), nullable=False))
    op.add_column("projects", sa.Column("description", sa.String(), nullable=True))
    op.add_column("projects", sa.Column("version", sa.Integer(), nullable=False))
    op.add_column("projects", sa.Column("owner_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        None, "projects", "users", ["owner_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "projects", type_="foreignkey")
    op.drop_column("projects", "owner_id")
    op.drop_column("projects", "version")
    op.drop_column("projects", "description")
    op.drop_column("projects", "name")
    op.drop_constraint(None, "project_members", type_="foreignkey")
    op.drop_constraint(None, "project_members", type_="foreignkey")
    op.create_foreign_key(
        op.f("project_members_project_id_fkey"),
        "project_members",
        "projects",
        ["project_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("project_members_user_id_fkey"),
        "project_members",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(None, "documents", type_="foreignkey")
    op.create_foreign_key(
        op.f("documents_project_id_fkey"),
        "documents",
        "projects",
        ["project_id"],
        ["id"],
    )
    op.drop_column("documents", "doc_type")
    op.drop_column("documents", "s3_key")
    op.drop_column("documents", "size")
    op.drop_column("documents", "name")
    # ### end Alembic commands ###
